### ISSUE TITLE
Ошибка при запросe auth/logout - AttributeError: 'SQLAlchemyUserDatabase' object has no attribute 'get_by_token'

### ISSUE THREAD

**Issue by elBukhara** [elBukhara/fastapi-users#1]
Работаю я c BearerTransport и DatabaseStrategy.

Все взаимодействия c auth/login и auth/register работают без упреков, передавая сам токен, но авторизованный пользователь не может выйти с учетной записи. При таком действие в UI swagger выходит такая ошибка:

![Снимок экрана_10-9-2024_135018_localhost](https://github.com/user-attachments/assets/2c0c7ce7-b19c-4f80-80da-7b281d00812c)

На консоли выходит такая ошибка:
```
INFO:     127.0.0.1:62034 - "POST /auth/logout HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__       
    await super().__call__(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__      
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__ 
    raise exc
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__ 
    await self.app(scope, receive, _send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi\dependencies\utils.py", line 611, in solve_dependencies
    solved = await call(**solved_result.values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<makefun-gen-0>", line 2, in current_user_token_dependency
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi_users\authentication\authenticator.py", line 92, in current_user_token_dependency
    return await self._authenticate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi_users\authentication\authenticator.py", line 170, in _authenticate
    user = await strategy.read_token(token, user_manager)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\users (fastapi)\.venv\Lib\site-packages\fastapi_users\authentication\strategy\db\strategy.py", 
line 33, in read_token
    access_token = await self.database.get_by_token(token, max_age)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SQLAlchemyUserDatabase' object has no attribute 'get_by_token'
```

Основная директория аутенфикации/авторизации находится в ```app/auth```

**Comment by mahenzon** [comment]
В модельке AccessToken поменяйте на `AccessTokenDatabase`
https://github.com/elBukhara/fastapi-users/blob/d3fa7914f92730e3cdf8abef9c6e4896aca95af3/app/auth/models/accesstoken.py#L26
